# Generated by Django 5.0.1 on 2024-01-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='./../media/profile_pics/default.jpg', upload_to='profile_pics'),
        ),
    ]
